alias v='vtex'
alias vb='vtex browse'
alias vbqr='vtex browse --qr'
alias vd='vtex deploy'
alias vil='vtex install'
alias vl='vtex link'
alias vlc='vtex link --clean'
alias vlv='vtex link --verbose'
alias vlcv='vtex link --clean --verbose'
alias vlvc='vtex link --clean --verbose'
alias vls='vtex list'
alias vlin='vtex login'
alias vlout='vtex logout'
alias vp='vtex publish'
alias vs='vtex switch'
alias vu='vtex unlink'
alias vua='vtex unlink --all'
alias vwd='vtex workspace delete'
alias vwu='vtex workspace use'


# Commands that wasn't created an alias

# alias v='vtex autoupdate'
# alias v='vtex deprecate'
# alias v='vtex deps'
# alias v='vtex edition'
# alias v='vtex help'
# alias v='vtex init'
# alias v='vtex local'
# alias v='vtex release'
# alias v='vtex setup'
# alias v='vtex undeprecate'
# alias v='vtex uninstall'
# alias v='vtex update'
# alias v='vtex whoami'
